import React from 'react'
import Script from 'next/script'

const contact = () => {
  return (
    <div>
       <Script>
      {`alert("Contact Facebook")`}
    </Script>
      Contact
    </div>
  )
}

export default contact

export const metadata = {
  title: "Facebook - Contact",
  description: "Generated by create next app",
};
