import React from 'react'
import Script from 'next/script'

const about = () => {
  return (
    <div>
      About
    </div>
  )
}

export default about

export const metadata = {
  title: "About Facebook - Connect with world!",
  description: "Generated by create next app",
};
